document:
  name: ConciliaWeb
  description: |
    ConciliaWeb è la piattaforma dell'Autorità per le garanzie nelle comunicazioni, semplice e interattiva, per la risoluzione delle controversie tra utenti e operatori di telefonia, Internet e Pay Tv.
  tags:
    - ConciliaWeb
    - Corecom
    - Operatori
