document:
  name: Musei Civici di Palazzo Pianetti
  description: |
    Sito istituzionale dei Musei Civici di Palazzo Pianetti
  tags:
    - Musei Civici di Palazzo Pianetti
    - Opere
    - Arte
    - Museo
